local map = vim.keymap.set
local actions = require("config.actions")

map("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
map("n", "<leader>d", vim.diagnostic.open_float, { desc = "Line diagnostics" })
map("n", "<leader>w", actions.save, { desc = "Save file" })
map("n", "<D-b>", actions.toggle_sidebar, { desc = "Toggle sidebar" })
map("i", "<D-b>", actions.toggle_sidebar_from_insert, { desc = "Toggle sidebar" })
map("i", "<lt>D-b>", actions.toggle_sidebar_from_insert, { desc = "Toggle sidebar" })
map("n", "<D-l>", actions.select_line, { desc = "Select line" })
map("i", "<D-l>", actions.select_line_from_insert, { desc = "Select line" })
map("i", "<lt>D-l>", actions.select_line_from_insert, { desc = "Select line" })
map("n", "<D-r>", actions.rename_symbol, { desc = "Rename symbol" })
map("i", "<D-r>", actions.rename_symbol_from_insert, { desc = "Rename symbol" })
map("i", "<lt>D-r>", actions.rename_symbol_from_insert, { desc = "Rename symbol" })
map("n", "<D-D>", actions.duplicate_line_down, { desc = "Duplicate line down" })
map("i", "<D-D>", actions.duplicate_line_down_from_insert, { desc = "Duplicate line down" })
map("n", "<D-S-d>", actions.duplicate_line_down, { desc = "Duplicate line down" })
map("i", "<D-S-d>", actions.duplicate_line_down_from_insert, { desc = "Duplicate line down" })
map("n", "<D-s>", actions.save, { desc = "Save file" })
map("i", "<D-s>", actions.save_from_insert, { desc = "Save file" })
map("i", "<lt>D-s>", actions.save_from_insert, { desc = "Save file" })
map("n", "<M-w>", actions.close_buffer, { desc = "Close buffer" })
map("i", "<M-w>", actions.close_buffer_from_insert, { desc = "Close buffer" })
map("n", "<D-w>", actions.close_buffer, { desc = "Close buffer" })
map("i", "<D-w>", actions.close_buffer_from_insert, { desc = "Close buffer" })
map("i", "<lt>D-w>", actions.close_buffer_from_insert, { desc = "Close buffer" })
map("n", "<C-D-Up>", actions.move_line_up, { desc = "Move line up" })
map("i", "<C-D-Up>", actions.move_line_up_from_insert, { desc = "Move line up" })
map("n", "<D-C-Up>", actions.move_line_up, { desc = "Move line up" })
map("i", "<D-C-Up>", actions.move_line_up_from_insert, { desc = "Move line up" })
map("n", "<C-D-Down>", actions.move_line_down, { desc = "Move line down" })
map("i", "<C-D-Down>", actions.move_line_down_from_insert, { desc = "Move line down" })
map("n", "<D-C-Down>", actions.move_line_down, { desc = "Move line down" })
map("i", "<D-C-Down>", actions.move_line_down_from_insert, { desc = "Move line down" })

-- Mirror terminal-style copy-on-select while preserving mouse support in Neovim UI.
map("x", "<LeftRelease>", "y", { silent = true, desc = "Copy selected text" })
