#!/usr/bin/env bash

if test ! $(which brew); then
    echo "Installing homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/cpojer/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew update
brew bundle
